tasks:
  - command: |
      ./scripts/install-tools.sh 
      ./scripts/run-terraform.sh
      ./scripts/ecr-push.sh
      ./scripts/kubernetes-deploy.sh

vscode:
  extensions:
    - "HashiCorp.terraform"
    - "ms-azuretools.vscode-docker"
    - "p1c2u.docker-compose"
