tasks:
  - command: ./install.sh
  - command: docker-compose up

vscode:
  extensions:
    - "HashiCorp.terraform"
    - "ms-azuretools.vscode-docker"

ports:
  - port: 3000
    name: "Microservice A"
    visibility: private

  - port: 3001
    name: "Microservice B"
    visibility: private
