tasks:
  - command: |
      ./scripts/terraform-deploy.sh 
      ./scripts/ecr-push.sh 
      ./scripts/kubernetes-deploy.sh

vscode:
  extensions:
    - "HashiCorp.terraform"
    - "ms-azuretools.vscode-docker"
    - "p1c2u.docker-compose"
