tasks:
  - name: "Setup"
    command: |
      ./scripts/env-setup.sh 
      ./kubernetes-infra/deploy-infra.sh
      ./scripts/env-auth.sh 
      ./microservice-a/app-deploy.sh
      ./microservice-b/app-deploy.sh
      ./kubernetes-infra/deploy-kubernetes.sh
      ./kubernetes-infra/deploy-backstage.sh
      gp sync-done "setup"

  - name: "Microservices"
    command: docker-compose up

  - name: "Backstage"
    command: |
      gp sync-await "setup"
      source ./backstage/backstage/env-setup.sh
      cd backstage/backstage
      yarn
      yarn dev

vscode:
  extensions:
    - "HashiCorp.terraform"
    - "ms-azuretools.vscode-docker"
    - "p1c2u.docker-compose"
    - "Intility.vscode-backstage"

ports:
  - port: 3000
    name: "Microservice A"
    visibility: private

  - port: 3001
    name: "Microservice B"
    visibility: private

  - port: 4000
    name: "Backstage"
    visibility: private
