apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicea
spec:
  selector:
    matchLabels:
      app: eks-sample-linux-app
  template:
    metadata:
      labels:
        app: eks-sample-linux-app
    spec:
      containers:
        - name: nginx
          image: 670483336223.dkr.ecr.us-east-1.amazonaws.com/microservice-a
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-service
spec:
  type: LoadBalancer
  selector:
    app: eks-sample-linux-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
