version: '3.0'

services:
  microservice-a:
    build:
      context: ./microservice-a
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
  
  microservice-b:
    build:
      context: ./microservice-b
      dockerfile: Dockerfile
    ports:
    - "3001:3001"