app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:4000

organization:
  name: Kumquat

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", "http:", "https:"]
  cors:
    origin: http://localhost:4000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ":memory:"

aws:
  mainAccount:
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    region: us-east-1

kubernetes:
  serviceLocatorMethod:
    type: "multiTenant"
  clusterLocatorMethods:
    # - type: localKubectlProxy
    - type: "config"
      clusters:
        - url: ${AWS_EKS_CLUSTER_URL}
          name: "my-cluster-eks"
          oidc: ${AWS_OIDC_URL}
          caData: ${AWS_EKS_CA}
          authProvider: "aws"

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration

  rules:
    - allow: [Component, System, API, Resource, Location]

  locations:
    - type: file
      target: ../../../../microservice-a/backstage.yaml

    - type: file
      target: ../../../../microservice-b/backstage.yaml

    - type: file
      target: ../../core.yaml
