---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: microservices
  description: Backtage application
spec:
  owner: app-devs
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: app-devs
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
  description: Backtage application
spec:
  owner: platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    "backstage.io/kubernetes-label-selector": "app=backstage"
spec:
  type: service
  lifecycle: production
  owner: platform
  system: backstage
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres-database
  annotations:
    "backstage.io/kubernetes-label-selector": "app=backstage"
spec:
  type: database
  lifecycle: production
  owner: platform
  system: backstage
