apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicea
spec:
  selector:
    matchLabels:
      app: microservice-a
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      containers:
        - name: nginx
          image: {{ .Values.microservice_a }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-a-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: microservice-a
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microserviceb
spec:
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
    spec:
      containers:
        - name: nginx
          image: {{ .Values.microservice_b }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-b-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: microservice-b
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
