apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: roadiehq/community-backstage-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7000
          envFrom:
            - secretRef:
                name: postgres-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
spec:
  type: LoadBalancer
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: http
