# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: microservice-a
  annotations:
    "backstage.io/kubernetes-label-selector": "app=microservice-a"
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
